name: Production Tag Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  release:
    type: [released]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install mesh
        run: yarn add @graphql-mesh/cli
      - name: Create temp env file
        run:
          echo "NEXT_PUBLIC_MAGENTO_URL=https://mcstaging.mobelringen.no/graphql" >> .env &&
          echo "NEXT_PUBLIC_HYGRAPH_URL=https://eu-central-1-shared-euc1-02.cdn.hygraph.com/content/clygve7j202ye07wbl0r8qgey/staging" >> .env
          echo "NEXT_PUBLIC_HYGRAPH_API_KEY=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdjbXMtbWFpbi1wcm9kdWN0aW9uIn0.eyJ2ZXJzaW9uIjozLCJpYXQiOjE3Mjg5MDM4MjIsImF1ZCI6WyJodHRwczovL2FwaS1ldS1jZW50cmFsLTEtc2hhcmVkLWV1YzEtMDIuaHlncmFwaC5jb20vdjIvY2x5Z3ZlN2oyMDJ5ZTA3d2JsMHI4cWdleS9zdGFnaW5nIiwibWFuYWdlbWVudC1uZXh0LmdyYXBoY21zLmNvbSJdLCJpc3MiOiJodHRwczovL21hbmFnZW1lbnQtZXUtY2VudHJhbC0xLXNoYXJlZC1ldWMxLTAyLmh5Z3JhcGguY29tLyIsInN1YiI6Ijg4NjJmOWI1LTkzNmMtNDljZi1hODNmLTEwODE3MDliMGI1YiIsImp0aSI6ImNtMjh3cDNlODAzODMwN3Z6MnRjcThrMmYifQ.nUUmLSyREWR2ybReu697ySqg16jU-c0yinY9r4bxTiDM06N6NdWxUeSlDwt9bmjceqskbeQS19N9qXdmT5oLHrUNFnkXcfD50kl0vTx-Cf2KqZP7cdwH52SYEtgqs1UyWKZIZ_VGBystDJvuVL9ssUWV-GeZNpAbwuYMwl2ZNQ_2MnxhJQm3YmejAKxhXAjMY_e1ukI3dLJfDZ1Un4XHztgR2gZvs8wbuWk2FNjwvf-PTToLBVtUvNCwSDf1Tjop5-J5zaQ1o3oGludTys_UOIr4SLnqgrIuR8zKZJAZ69arRwMs9_rlvEvgI0ydWCXZbXW6dFaMaRUUQg1Ujv7zB44Z3lEBWW9zcb10PqTElYtBN5heIXtorMehMIasov2sGs49UTDADQsyOFkKkHh67i7HqvhizNclOjZJCaGkJhGdsMM_ZSvebCspB5V40ptTYUvBgxmceMfDVLPjekn-bvuUR_ryyy5ZpnM6IiYatbCJAFcGo5sn8y3cfkdYm9u_1k400ymNhe6Px87ypFP3cverxKrbjsfgP8ukZP9bfXSR3WdPrmIUcwzes3a2hOJTcx0GML2Nhu5jza4elBybGN3F0QYBPo46jZAWb-F0bpXihbG-0hx2KwrF3dzmgpJDeNur2lfQ7_dXiafPHy-ZU5R9KikyklJ4MAde4WopmLQ" >> .env &&
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
